### ISSUE TITLE
Regarding the issue of 'source' variables

### ISSUE THREAD

**Issue by TuZi-94** [ZFTurbo/Music-Source-Separation-Training#103]
UnboundLocalError: local variable'sourcereferenced before assignment 

Do I need to define the global variable 'source' in the 'dataset.py'？

**Comment by ZFTurbo** [comment]
Hello. Can you provide more information please?

**Comment by TuZi-94** [comment]
**Thank you very much for your reply. Below are the errors encountered while running the code：**

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) Path: /22wanglili/sqs_code/Music-Source-Separation-Training-main/DATA/train/Song 1/vocals.flac

**Comment by ZFTurbo** [comment]
What is the length of `DATA/train/Song 1/vocals.flac` in seconds? I think I know the problem.

**Comment by TuZi-94** [comment]
Thank you very much for your reply. My data format is single channel data, and the duration of each data is 5 seconds. I found that it seems to be an error in the **dataset.py** and **load_chunk function**.If **X** is single channel data, then it seems unable to be computed with a matrix **pad**.So I think it's possible to change the **load_chunk function** so that even after transforming the single sequence data, operations can still be performed.

**Comment by ZFTurbo** [comment]
I did a fix for such cases. Can you please check if it works now?

**Comment by wanggle123** [comment]
Thank you very much for your help, it was able to work successfully.
