### ISSUE TITLE
MDX23C checkpoint training

### ISSUE THREAD

**Issue by neiki1** [ZFTurbo/Music-Source-Separation-Training#13]
Hi, I am a beginner in machine learning. I want to try to train the MUSDB18HQ dataset with additional STEMS. Am I correct that I can do this and I don't need to download 20GB dataset?

I tried to run the training but got the answer that there are 0 tracks in the dataset. How many VALID (TEST) tracks would you recommend to upload in relation to the whole dataset, 20% is ok?
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/139687082/a0a7165c-b17b-4bb4-b57e-6519ec44aa3b)
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/139687082/f9e55d29-cf61-4d6d-a309-cab0c52a06f4)
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/139687082/e4b0c6a2-944c-494b-9f6d-9383c5347ba9)
test/valid tracks:
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/139687082/2aa1fa01-f379-42d7-a7f0-90ebd85c611d)

**Comment by ZFTurbo** [comment]
1) Remove metadata_1.pkl from `results` directory
2) `--data_path` - better provide full path to the directory
3) 10-20% for validation is ok

**Comment by neiki1** [comment]
Спасибо, проблема решилась после удаления metadata_1.pkl из папка results.
Подскажи пожалуйста, обязательно ли иметь видеокарту с более чем 48 GB видеопамяти чтобы дотренировать датасет MUSDB18HQ? Или возможно уменьшить training.batch_size и training.gradient_accumulation_steps и просто продолжить тренировку?
