### ISSUE TITLE
Increasing the speed of training

### ISSUE THREAD

**Issue by neiki1** [ZFTurbo/Music-Source-Separation-Training#14]
@ZFTurbo, Привет еще раз, заметил что Вы из России/Казахстана, приятно видеть это)
У меня появилась идея, я портировал Ваш скрипт на Google Kaggle (выложу его на GitHub чуть позже), как думаете, возможно ли ускорить тренировку модели путем запуска алгоритма на нескольких серверах?
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/139687082/88d0d227-4d1e-4f2c-a604-8c0ce6b01391)

Представим, что у нас есть 4 бесплатных аккаунта Google Collab с GPU T4. Было бы здорово если можно на 4 аккаунтах запустить скрипт тренировки, и Google Коллабы обменивались через DDP (PyTorch Distributed Data Parallel) или Horovod (фреймворк, разработанный Uber, для распределенного обучения моделей глубокого обучения).

Это сильно ускорит тренировку моделей, и выйдет бесплатно, чем аренда сервера с 8xTESLA T4.
Я готов написать код который будет запускать на разных Google Collab аккаунтах скрипт. Нужно лишь связать сервера.

Я не знаю тонкостей обучения моделей, хочу послушать Ваше мнение на счет этого, еще раз спасибо за большой вклад в сферу нейросетей и музыки.

Также подскажите пожалуйста кол-во треков в Вашем датасете для mdx23c. Я нашел отличный ресурс где можно получить оригинальные стемсы популярных треков студийного качества. https://songstems.net/ Возможно это будет полезно для вас) Хотелось бы собрать датасет но возможно будет проблема с загрузкой его куда-либо, авторские права и DMCA как никак(
Есть возможность, получить ваш Телеграм?

**Comment by ZFTurbo** [comment]
Для распределенных вычислений нужно переписать train.py с поддержкой Distributed Data Parallel. Я не особо спец в этом и мне пока это было особо не нужно. Если вдруг напишешь будет хорошо если поделишься им в рамках этого репозитория через Pull Request.

Мой датасет на котором я обучал MDX23C сейчас содержит несколько тысяч треков.
