### ISSUE TITLE
BS Roformer model

### ISSUE THREAD

**Issue by adderiyadriana90** [ZFTurbo/Music-Source-Separation-Training#18]
Hi, can you please advise. will you post the new BS Roformer trained model?

**Comment by ZFTurbo** [comment]
Weights were posted on main page:
https://github.com/ZFTurbo/Music-Source-Separation-Training?tab=readme-ov-file#vocal-models

**Comment by carlosalberto2000** [comment]
Just to avoid opening a new issue...
I thought the BS Roformer model was capable of separating instruments?
Or it depends on the training?

Sorry if it is a stupid question, I'm still learning.
