### ISSUE TITLE
inferencing

### ISSUE THREAD

**Issue by mcdthekid** [ZFTurbo/Music-Source-Separation-Training#21]
I tried to use a pretrained vocal model for bs roformer and this is the error i get, no idea how to fix it

PS C:\Users\matt\Downloads\Music-Source-Separation-Training-v.1.0.3\Music-Source-Separation-Training-v.1.0.3> python inference.py --model_type bs_roformer --config_path "C:\Users\matt\Downloads\model_bs_roformer_ep_317_sdr_12.9755.yaml.txt" --start_check_point 
"C:\Users\matt\Downloads\model_bs_roformer_ep_317_sdr_12.9755 (1).ckpt" --input_folder 
"C:\Users\matt\Downloads\input" --store_dir "C:\Users\matt\Downloads\Music" --device_ids 0
>> 
Instruments: ['vocals', 'other']
Traceback (most recent call last):
  File "inference.py", line 99, in <module>
    proc_folder(None)
  File "inference.py", line 75, in proc_folder
    model = get_model_from_config(args.model_type, config)
  File "C:\Users\matt\Downloads\Music-Source-Separation-Training-v.1.0.3\Music-Source-Separation-Training-v.1.0.3\utils.py", line 28, in get_model_from_config
    model = BSRoformer(
  File "<@beartype(models.bs_roformer.bs_roformer.BSRoformer.__init__) at 0x24e8d24f160>", line 98, in __init__
TypeError: __init__() got an unexpected keyword argument 'linear_transformer_depth'    
PS C:\Users\matt\Downloads\Music-Source-Separation-Training-v.1.0.3\Music-Source-Separation-Training-v.1.0.3>

**Comment by ZFTurbo** [comment]
You use config with old code from this repository. Update code and try again.
https://github.com/ZFTurbo/Music-Source-Separation-Training/archive/refs/heads/main.zip

**Comment by mcdthekid** [comment]
i got everything working but do u have a bs roformer model for extracting instrumentals? I have tried all three and so far I can only extract vocals, if i try other its also just vocals

**Comment by mcdthekid** [comment]
how do I do that?

**Comment by ZFTurbo** [comment]
Currently it's not supported in code. But it's just a 1-2 lines to add. I will do later today.

**Comment by mcdthekid** [comment]
please send when you do, thank you

**Comment by ZFTurbo** [comment]
I updated inference.py. Use `--extract_instrumental` parameter to get instrumental part.
