### ISSUE TITLE
Ensemble Demixing using multiple models at once?

### ISSUE THREAD

**Issue by jtishy** [ZFTurbo/Music-Source-Separation-Training#25]
Hello, I have the seperation training setup properly and am able to utilize which model I choose.  This is great, but I see that the leader boards have first place using MDX23C and BS Roformer (https://mvsep.com/quality_checker/entry/6240).

I've tried but can't get multiple models to be used at once - is there a way for us to use two models in an ensemble mode at once like the top of the leaderboards did using this separation training script?  

Thanks so much!

**Comment by ZFTurbo** [comment]
There is no ensemble script available in this repository. But you can do ensemble manually or write simple script for this.

Also as @jarredou mentioned you can use either mvsep.com or Collab to have en ensemble result.

**Comment by ZFTurbo** [comment]
I deicded to add ensemble script to this repository:

https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/ensemble.py

**Comment by jtishy** [comment]
You rock ZFTurbo!!!!!  Can't wait to play around with this and the weights.  I wonder if MVsep has the weights on some of the leaderboard points.
