### ISSUE TITLE
BandIt Plus weights

### ISSUE THREAD

**Issue by SorrHash** [ZFTurbo/Music-Source-Separation-Training#29]
I think there is a mistake here
model_bandit_plus_dnr_sdr_11.47`.chpt` ,it must be `.ckpt` file not `.chpt` file
am i right ?

**Comment by ZFTurbo** [comment]
It's probably error in naming. But it should work fine with this name.

**Comment by SorrHash** [comment]
no, when i test model_mdx23c_ep_168_sdr_7.0207.ckpt with his config, it worked fine.
but model_bandit_plus_dnr_sdr_11.47.chpt it didn't work and also when i rename it to .ckpt still not working.

**Comment by ZFTurbo** [comment]
How did you run it?

**Comment by SorrHash** [comment]
![Screenshot 2024-05-21 203546](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/114016987/3b99b155-ecc6-4cad-ac20-0bbea080a1f0)
![21](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/114016987/d95ad930-aa09-4e77-8c70-1c8cb7bf41eb)

**Comment by ZFTurbo** [comment]
BandIt model as I know is not supported by UVR. You need to use inference.py script from this repository.

**Comment by SorrHash** [comment]
Ok, Thx
