### ISSUE TITLE
Training  colab for custom dataset

### ISSUE THREAD

**Issue by SutirthaChakraborty** [ZFTurbo/Music-Source-Separation-Training#3]
Hi, 
This is a really great repo. Can you share a sample colab notebook, that we can link with drive and train on different custom datasets? Also, I am a newbie in this domain. What should be the folder structure?

I have two folders 
-   Tabla wav files (Indian musical instrument)
-  Dhaak wav files(Indian musical instrument)

**Comment by ZFTurbo** [comment]
Hello. Can you explain what you expect your model to do in the end?

**Comment by SutirthaChakraborty** [comment]
Separate the two different sounds from a mix track. Or separate the male vocals and female vocals from a duet song track.

**Comment by ZFTurbo** [comment]
> Separate the two different sounds from a mix track. Or separate the male vocals and female vocals from a duet song track. I have downloaded [VocalSet](https://paperswithcode.com/dataset/vocalset#:~:text=VocalSet%20(VocalSet%3A%20A%20Singing%20Voice%20Dataset)&text=all%205%20vowels.-,Existing%20singing%20voice%20datasets%20aim%20to%20capture%20a%20focused%20subset,a%20range%20of%20voice%20types.) that has male singing vocals and female singing vocals. My idea is to mix the two vocals for training, and then try to separate them back. Will that work?

I think it can work. But dataset is limited, so I don't know the behavior on real data after.

**Comment by SutirthaChakraborty** [comment]
Can you give us a colab script, in the repo, that can easily do this type of task on a custom dataset?

**Comment by ZFTurbo** [comment]
I don't use collab. I have no plans to add code there. If someone do on the basis on my code, I'll be happy.

**Comment by SutirthaChakraborty** [comment]
Can you please share me the link or details of the folder structure in which I can put the data?
Right now  i have 
## Vocalset Folder Structure

The `Vocalset` directory contains two subdirectories for vocal recordings categorized by gender. Here's the detailed structure:

- `Vocalset/`
  - `malevocals/`
    - `file1.wav`
    - `file2.wav`
    - `...`
  - `femalevocals/`
    - `file1.wav`
    - `file2.wav`
    - `...`

Each `wav` file represents a separate vocal recording.

**Comment by ZFTurbo** [comment]
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/docs/dataset_types.md

You need `--dataset_type 2`. 
As "--data_path" use system path to "Vocalset"
And in config use "malevocals" and "femalevocals" as stem names.

**Comment by SutirthaChakraborty** [comment]
Thank you so much.
