### ISSUE TITLE
Ensemble Script

### ISSUE THREAD

**Issue by shirounanashi** [ZFTurbo/Music-Source-Separation-Training#32]
Regarding the ensemble script, an explanation of the types could be added, and also, when I use the “fft” types, the following error occurs
```
Traceback (most recent call last):
  File "G:\ensemble\ensemble.py", line 162, in <module>
    ensemble_files(None)
  File "G:\ensemble\ensemble.py", line 156, in ensemble_files
    res = average_waveforms(data, weights, args.type)
  File "G:\ensemble\ensemble.py", line 89, in average_waveforms
    spec = stft(pred_track[i], 2048, 1024)
  File "G:\ensemble\ensemble.py", line 14, in stft
    spec_left = librosa.stft(wave_left, nfft, hop_length=hl)
TypeError: stft() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
```
With the following command
`python ensemble.py --files "1_01. Wings of Reality_(Vocals).flac" "1_01. Wings of Reality_MDX23C-8KFFT-InstVoc_HQ_(Vocals).flac" --type avg_fft --weights 2 1`

**Comment by shirounanashi** [comment]
Yes, this is the installed version 0.10.2.post1

**Comment by shirounanashi** [comment]
I tested it on librosa version 0.9.2 and it didn't give me the problem, but this warning appeared:
`ensemble.py:15: FutureWarning: Pass n_fft=2048 as keyword args. From version 0.10 passing these as positional arguments will result in an error`
Also, I had to install a version of numpy lower than 1.24
But then an error appeared that I couldn't fix:
```
Traceback (most recent call last):
  File "G:\ensemble\ensemble.py", line 162, in <module>
    ensemble_files(None)
  File "G:\ensemble\ensemble.py", line 158, in ensemble_files
    sf.write(args.output, res.T, sr, 'FLOAT')
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 343, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'res.wav': Format not recognised.
```

**Comment by ZFTurbo** [comment]
Can you check if res.wav is correct wav file? Can you post it here?

**Comment by shirounanashi** [comment]
[res.zip](https://github.com/user-attachments/files/15782812/res.zip)
Here, this is the file generated. Apparently it's just a corrupt file

**Comment by ZFTurbo** [comment]
How did you generate res.wav?

**Comment by ZFTurbo** [comment]
Can you post results of this line:
```
print('Result shape: {}'.format(res.shape))
```

**Comment by shirounanashi** [comment]
@ZFTurbo Here, the shape result
`Result shape: (15631980, 2)`
about how I generated the file, I just ran the command, after installing the versions of librosa and numpy, it started generating the file, only this way, corrupted

**Comment by ZFTurbo** [comment]
Can you try change line:

```
sf.write(args.output, res.T, sr, 'FLOAT')
```

to 

```
sf.write(args.output, res, sr, 'FLOAT')
```

I will check myself later today

**Comment by shirounanashi** [comment]
It worked! In fft, because in wave, it had the problem that fft had now. It seems that changing this results in solving the problem of one and making the other stop working

**Comment by shirounanashi** [comment]
Oh, and also, what does fft do? I think wave is an ensemble of waveforms, but I have no idea what fft is, and the same goes for median, which UVR doesn't have. It would be good to add a description of the types in the readme

**Comment by shirounanashi** [comment]
I've tested the latest commit, and the script is working in the latest version of librosa, both wave and fft! Now all that's needed is an explanation of the types to close this issue!

**Comment by ZFTurbo** [comment]
I added documentation:
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/docs/ensemble.md

**Comment by shirounanashi** [comment]
Thanks, that cleared up my doubts about the types! I'll close the issue
