### ISSUE TITLE
error in demix_track function 

### ISSUE THREAD

**Issue by anvuew** [ZFTurbo/Music-Source-Separation-Training#36]
i am training mel_band_roformer and changed train.py line 500 `if 0` to `if 1`
when starting SDR evaluation 
```
  File "train.py", line 517, in <module>
    train_model(None)
  File "train.py", line 501, in train_model
    sdr_avg = valid(model, args, config, device, verbose=False)
  File "train.py", line 136, in valid
    res = demix_track(config, model, mixture, device)
  File "utils.py", line 130, in demix_track
    result[..., start:start+l] += x[j][..., :l].cpu() * window[..., :l]
RuntimeError: The size of tensor a (131418) must match the size of tensor b (131584) at non-singleton dimension 1
```
`arr.size()` is `torch.Size([4, 2, 131584])` 
`x.size()` is `torch.Size([4, 2, 131418])`
![image](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/80335796/923d7293-8e91-48d7-98a3-12246a9d4350)

**Comment by anvuew** [comment]
well I chosed the wrong config.

**Comment by YuanCrimson** [comment]
@anvuew hi, there. Can you please tell me how you solved this problem?
I just find the same error.

**Comment by anvuew** [comment]
> @anvuew hi, there. Can you please tell me how you solved this problem? I just find the same error. 
 

> well I chosed the wrong config.

I just used the default config (configs/config_vocals_mel_band_roformer.yaml) instead of viperx's config.

**Comment by YuanCrimson** [comment]
> > @anvuew hi, there. Can you please tell me how you solved this problem? I just find the same error.
> 
> > well I chosed the wrong config.
> 
> I just used the default config (configs/config_vocals_mel_band_roformer.yaml) instead of viperx's config.

When I use the default config(configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml), the audio.chunk_size is 352800, everything is ok. Training and validation are both completed.
But when I change it to 131584, the error occurs again. I guess the preprocess of loading data is not consistent with the way to create windowingArray.

**Comment by anvuew** [comment]
> > > @anvuew hi, there. Can you please tell me how you solved this problem? I just find the same error.
> > 
> > 
> > > well I chosed the wrong config.
> > 
> > 
> > I just used the default config (configs/config_vocals_mel_band_roformer.yaml) instead of viperx's config.
> 
> When I use the default config(configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml), the audio.chunk_size is 352800, everything is ok. Training and validation are both completed. But when I change it to 131584, the error occurs again. I guess the preprocess of loading data is not consistent with the way to create windowingArray.

The valid values for `chunk_size` may depend on `hop_length`.

**Comment by YuanCrimson** [comment]
> > > > @anvuew hi, there. Can you please tell me how you solved this problem? I just find the same error.
> > > 
> > > 
> > > > well I chosed the wrong config.
> > > 
> > > 
> > > I just used the default config (configs/config_vocals_mel_band_roformer.yaml) instead of viperx's config.
> > 
> > 
> > When I use the default config(configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml), the audio.chunk_size is 352800, everything is ok. Training and validation are both completed. But when I change it to 131584, the error occurs again. I guess the preprocess of loading data is not consistent with the way to create windowingArray.
> 
> The valid values for `chunk_size` may depend on `hop_length`.

You're right. The chunk size should be an integer multiple of the hop length to ensure the alignment of the slice length.
