### ISSUE TITLE
Bandit v2 inference error:  Unexpected key(s) in state_dict:  "epoch", "global_step", "pytorch-lightning_version", "state_dict", "loops", "callbacks", "optimizer_states", "lr_schedulers".

### ISSUE THREAD

**Issue by Cornox** [ZFTurbo/Music-Source-Separation-Training#41]
Hi, I'm using windows + anaconda.
I've downloaded the bandit v2 model "checkpoint-eng.ckpt"  from https://zenodo.org/records/12701995 (which was linked in the https://github.com/kwatcharasupat/bandit-v2 repository).
I've put the model in the models folder, but when I run the following command I'm getting an error:

(msst_2) C:\Users\dreiD\Documents\github\Music-Source-Separation-Training>python inference.py --model_type bandit_v2 --config_path configs\config_dnr_bandit_v2_mus64.yaml  --start_check_point models\checkpoint-eng.ckpt --input_folder input --store_dir separation_results
Start from checkpoint: models\checkpoint-eng.ckpt
Traceback (most recent call last):
  File "C:\Users\dreiD\Documents\github\Music-Source-Separation-Training\inference.py", line 129, in <module>
    proc_folder(None)
  File "C:\Users\dreiD\Documents\github\Music-Source-Separation-Training\inference.py", line 109, in proc_folder
    model.load_state_dict(state_dict)
  File "C:\Users\dreiD\anaconda3\envs\msst_2\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Bandit:
        Missing key(s) in state_dict: "stft.window", "istft.window", "band_split.norm_fc_modules.0.combined.0.weight", "band_split.norm_fc_modules.0.combined.0.bias", "band_split.norm_fc_modules.0.combined.1.weight", "band_split.norm_fc_modules.0.combined.1.bias", "band_split.norm_fc_modules.1.combined.0.weight", "band_split.norm_fc_modules.1.combined.0.bias", "band_split.norm_fc_modules.1.combined.1.weight", "band_split.norm_fc_modules.1.combined.1.bias", "band_split.norm_fc_modules.2.combined.0.weight", ....
 ...
"band_split.norm_fc_modules.63.combined.0.bias", "band_split.norm_fc_modules.63.combined.1.weight", "band_split.norm_fc_modules.63.combined.1.bias", "tf_model.seqband.0.norm.weight", "tf_model.seqband.0.norm.bias", "tf_model.seqband.0.rnn.weight_ih_l0", "tf_model.seqband.0.rnn.weight_hh_l0", "tf_model.seqband.0.rnn.bias_ih_l0", "tf_model.seqband.0.rnn.bias_hh_l0", "tf_model.seqband.0.rnn.weight_ih_l0_reverse", "tf_model.seqband.0.rnn.weight_hh_l0_reverse", "tf_model.seqband.0.rnn.bias_ih_l0_reverse", "tf_model.seqband.0.rnn.bias_hh_l0_reverse", "tf_model.seqband.0.fc.weight", "tf_model.seqband.0.fc.bias", "tf_model.seqband.2.norm.weight", "tf_model.seqband.2.norm.bias", "tf_model.seqband.2.rnn.weight_ih_l0", "tf_model.seqband.2.rnn.weight_hh_l0", "tf_model.seqband.2.rnn.bias_ih_l0", "tf_model.seqband.2.rnn.bias_hh_l0", "tf_model.seqband.2.rnn.weight_ih_l0_reverse", "tf_model.seqband.2.rnn.weight_hh_l0_reverse", "tf_model.seqband.2.rnn.bias_ih_l0_reverse", "tf_model.seqband.2.rnn.bias_hh_l0_reverse", "tf_model.seqband.2.fc.weight", "tf_model.seqband.2.fc.bias", "tf_model.seqband.4.norm.weight", "tf_model.seqband.4.norm.bias", "tf_model.seqband.4.rnn.weight_ih_l0", "tf_model.seqband.4.rnn.weight_hh_l0", "tf_model.seqband.4.rnn.bias_ih_l0", "tf_model.seqband.4.rnn.bias_hh_l0", "tf_model.seqband.4.rnn.weight_ih_l0_reverse", "tf_model.seqband.4.rnn.weight_hh_l0_reverse", "tf_model.seqband.4.rnn.bias_ih_l0_reverse", "tf_model.seqband.4.rnn.bias_hh_l0_reverse", "tf_model.seqband.4.fc.weight", "tf_model.seqband.4.fc.bias", "tf_model.seqband.6.norm.weight", "tf_model.seqband.6.norm.bias", "tf_model.seqband.6.rnn.weight_ih_l0", ...
"tf_model.seqband.30.rnn.weight_ih_l0", "tf_model.seqband.30.rnn.weight_hh_l0", "tf_model.seqband.30.rnn.bias_ih_l0", "tf_model.seqband.30.rnn.bias_hh_l0", "tf_model.seqband.30.rnn.weight_ih_l0_reverse", "tf_model.seqband.30.rnn.weight_hh_l0_reverse", "tf_model.seqband.30.rnn.bias_ih_l0_reverse", "tf_model.seqband.30.rnn.bias_hh_l0_reverse", "tf_model.seqband.30.fc.weight", "tf_model.seqband.30.fc.bias", "mask_estim.speech.freq_weights/0", "mask_estim.speech.freq_weights/1", "mask_estim.speech.freq_weights/2", "mask_estim.speech.freq_weights/3", "mask_estim.speech.freq_weights/4", "mask_estim.speech.freq_weights/5", "mask_estim.speech.freq_weights/6", "mask_estim.speech.freq_weights/7", "mask_estim.speech.freq_weights/8", "mask_estim.speech.freq_weights/9", "mask_estim.speech.freq_weights/10", "mask_estim.speech.freq_weights/11", "mask_estim.speech.freq_weights/12", "mask_estim.speech.freq_weights/13", "mask_estim.speech.freq_weights/14", "mask_estim.speech.freq_weights/15", "mask_estim.speech.freq_weights/16", "mask_estim.speech.freq_weights/17", "mask_estim.speech.freq_weights/18", "mask_estim.speech.freq_weights/19", "mask_estim.speech.freq_weights/20", "mask_estim.speech.freq_weights/21", "mask_estim.speech.freq_weights/22", "mask_estim.speech.freq_weights/23", "mask_estim.speech.freq_weights/24", "mask_estim.speech.freq_weights/25", "mask_estim.speech.freq_weights/26", "mask_estim.speech.freq_weights/27", "mask_estim.speech.freq_weights/28", "mask_estim.speech.freq_weights/29", "mask_estim.speech.freq_weights/30", "mask_estim.speech.freq_weights/31", "mask_estim.speech.freq_weights/32", "mask_estim.speech.freq_weights/33", "mask_estim.speech.freq_weights/34", "mask_estim.speech.freq_weights/35", "mask_estim.speech.freq_weights/36", "mask_estim.speech.freq_weights/37", "mask_estim.speech.freq_weights/38", "mask_estim.speech.freq_weights/39", "mask_estim.speech.freq_weights/40", "mask_estim.speech.freq_weights/41", "mask_estim.speech.freq_weights/42", "mask_estim.speech.freq_weights/43", "mask_estim.speech.freq_weights/44", "mask_estim.speech.freq_weights/45", "mask_estim.speech.freq_weights/46", "mask_estim.speech.freq_weights/47", "mask_estim.speech.freq_weights/48", "mask_estim.speech.freq_weights/49", "mask_estim.speech.freq_weights/50", "mask_estim.speech.freq_weights/51", "mask_estim.speech.freq_weights/52", "mask_estim.speech.freq_weights/53", "mask_estim.speech.freq_weights/54", "mask_estim.speech.freq_weights/55", "mask_estim.speech.freq_weights/56", "mask_estim.speech.freq_weights/57", "mask_estim.speech.freq_weights/58", "mask_estim.speech.freq_weights/59", "mask_estim.speech.freq_weights/60", "mask_estim.speech.freq_weights/61", "mask_estim.speech.freq_weights/62", "mask_estim.speech.freq_weights/63", "mask_estim.speech.norm_mlp.0.norm.weight", "mask_estim.speech.norm_mlp.0.norm.bias", "mask_estim.speech.norm_mlp.0.hidden.0.weight", "mask_estim.speech.norm_mlp.0.hidden.0.bias", "mask_estim.speech.norm_mlp.0.output.0.weight", "mask_estim.speech.norm_mlp.0.output.0.bias", "mask_estim.speech.norm_mlp.0.combined.0.weight", "mask_estim.speech.norm_mlp.0.combined.0.bias", "mask_estim.speech.norm_mlp.0.combined.1.0.weight", "mask_estim.speech.norm_mlp.0.combined.1.0.bias", "mask_estim.speech.norm_mlp.0.combined.2.0.weight", "mask_estim.speech.norm_mlp.0.combined.2.0.bias", "mask_estim.speech.norm_mlp.1.norm.weight", "mask_estim.speech.norm_mlp.1.norm.bias", "mask_estim.speech.norm_mlp.1.hidden.0.weight", "mask_estim.speech.norm_mlp.1.hidden.0.bias", "mask_estim.speech.norm_mlp.1.output.0.weight", "mask_estim.speech.norm_mlp.1.output.0.bias", "mask_estim.speech.norm_mlp.1.combined.0.weight", "mask_estim.speech.norm_mlp.1.combined.0.bias", "mask_estim.speech.norm_mlp.1.combined.1.0.weight", "mask_estim.speech.norm_mlp.1.combined.1.0.bias", "mask_estim.speech.norm_mlp.1.combined.2.0.weight", "mask_estim.speech.norm_mlp.1.combined.2.0.bias", "mask_estim.speech.norm_mlp.2.norm.weight", "mask_estim.speech.norm_mlp.2.norm.bias", "mask_estim.speech.norm_mlp.2.hidden.0.weight", "mask_estim.speech.norm_mlp.2.hidden.0.bias", "mask_estim.speech.norm_mlp.2.output.0.weight", "mask_estim.speech.norm_mlp.2.output.0.bias", "mask_estim.speech.norm_mlp.2.combined.0.weight", "mask_estim.speech.norm_mlp.2.combined.0.bias", "mask_estim.speech.norm_mlp.2.combined.1.0.weight", "mask_estim.speech.norm_mlp.2.combined.1.0.bias", "mask_estim.speech.norm_mlp.2.combined.2.0.weight", "mask_estim.speech.norm_mlp.2.combined.2.0.bias", "mask_estim.speech.norm_mlp.3.norm.weight", "mask_estim.speech.norm_mlp.3.norm.bias", "mask_estim.speech.norm_mlp.3.hidden.0.weight", ...
...
"mask_estim.speech.norm_mlp.63.norm.bias", "mask_estim.speech.norm_mlp.63.hidden.0.weight", "mask_estim.speech.norm_mlp.63.hidden.0.bias", "mask_estim.speech.norm_mlp.63.output.0.weight", "mask_estim.speech.norm_mlp.63.output.0.bias", "mask_estim.speech.norm_mlp.63.combined.0.weight", "mask_estim.speech.norm_mlp.63.combined.0.bias", "mask_estim.speech.norm_mlp.63.combined.1.0.weight", "mask_estim.speech.norm_mlp.63.combined.1.0.bias", "mask_estim.speech.norm_mlp.63.combined.2.0.weight", "mask_estim.speech.norm_mlp.63.combined.2.0.bias", "mask_estim.music.freq_weights/0", "mask_estim.music.freq_weights/1", "mask_estim.music.freq_weights/2", "mask_estim.music.freq_weights/3", "mask_estim.music.freq_weights/4", "mask_estim.music.freq_weights/5", "mask_estim.music.freq_weights/6", "mask_estim.music.freq_weights/7", "mask_estim.music.freq_weights/8", "mask_estim.music.freq_weights/9", "mask_estim.music.freq_weights/10", "mask_estim.music.freq_weights/11", "mask_estim.music.freq_weights/12", "mask_estim.music.freq_weights/13", "mask_estim.music.freq_weights/14", "mask_estim.music.freq_weights/15", "mask_estim.music.freq_weights/16", "mask_estim.music.freq_weights/17", "mask_estim.music.freq_weights/18", "mask_estim.music.freq_weights/19", "mask_estim.music.freq_weights/20", "mask_estim.music.freq_weights/21", "mask_estim.music.freq_weights/22", "mask_estim.music.freq_weights/23", "mask_estim.music.freq_weights/24", "mask_estim.music.freq_weights/25", "mask_estim.music.freq_weights/26", "mask_estim.music.freq_weights/27", "mask_estim.music.freq_weights/28", "mask_estim.music.freq_weights/29", "mask_estim.music.freq_weights/30", "mask_estim.music.freq_weights/31", "mask_estim.music.freq_weights/32", "mask_estim.music.freq_weights/33", "mask_estim.music.freq_weights/34", "mask_estim.music.freq_weights/35", "mask_estim.music.freq_weights/36", "mask_estim.music.freq_weights/37", "mask_estim.music.freq_weights/38", "mask_estim.music.freq_weights/39", "mask_estim.music.freq_weights/40", "mask_estim.music.freq_weights/41", "mask_estim.music.freq_weights/42", "mask_estim.music.freq_weights/43", "mask_estim.music.freq_weights/44", "mask_estim.music.freq_weights/45", "mask_estim.music.freq_weights/46", "mask_estim.music.freq_weights/47", "mask_estim.music.freq_weights/48", "mask_estim.music.freq_weights/49", "mask_estim.music.freq_weights/50", "mask_estim.music.freq_weights/51", "mask_estim.music.freq_weights/52", "mask_estim.music.freq_weights/53", "mask_estim.music.freq_weights/54", "mask_estim.music.freq_weights/55", "mask_estim.music.freq_weights/56", "mask_estim.music.freq_weights/57", "mask_estim.music.freq_weights/58", "mask_estim.music.freq_weights/59", "mask_estim.music.freq_weights/60", "mask_estim.music.freq_weights/61", "mask_estim.music.freq_weights/62", "mask_estim.music.freq_weights/63", "mask_estim.music.norm_mlp.0.norm.weight", "mask_estim.music.norm_mlp.0.norm.bias", "mask_estim.music.norm_mlp.0.hidden.0.weight", "mask_estim.music.norm_mlp.0.hidden.0.bias", "mask_estim.music.norm_mlp.0.output.0.weight", "mask_estim.music.norm_mlp.0.output.0.bias", "mask_estim.music.norm_mlp.0.combined.0.weight", "mask_estim.music.norm_mlp.0.combined.0.bias", "mask_estim.music.norm_mlp.0.combined.1.0.weight", "mask_estim.music.norm_mlp.0.combined.1.0.bias", "mask_estim.music.norm_mlp.0.combined.2.0.weight", "mask_estim.music.norm_mlp.0.combined.2.0.bias", "mask_estim.music.norm_mlp.1.norm.weight", "mask_estim.music.norm_mlp.1.norm.bias", "mask_estim.music.norm_mlp.1.hidden.0.weight", "mask_estim.music.norm_mlp.1.hidden.0.bias", "mask_estim.music.norm_mlp.1.output.0.weight", "mask_estim.music.norm_mlp.1.output.0.bias", "mask_estim.music.norm_mlp.1.combined.0.weight", "mask_estim.music.norm_mlp.1.combined.0.bias", "mask_estim.music.norm_mlp.1.combined.1.0.weight", "mask_estim.music.norm_mlp.1.combined.1.0.bias", "mask_estim.music.norm_mlp.1.combined.2.0.weight", "mask_estim.music.norm_mlp.1.combined.2.0.bias", "mask_estim.music.norm_mlp.2.norm.weight", "mask_estim.music.norm_mlp.2.norm.bias", "mask_estim.music.norm_mlp.2.hidden.0.weight", "mask_estim.music.norm_mlp.2.hidden.0.bias", "mask_estim.music.norm_mlp.2.output.0.weight", "mask_estim.music.norm_mlp.2.output.0.bias", "mask_estim.music.norm_mlp.2.combined.0.weight", "mask_estim.music.norm_mlp.2.combined.0.bias", "mask_estim.music.norm_mlp.2.combined.1.0.weight", "mask_estim.music.norm_mlp.2.combined.1.0.bias", "mask_estim.music.norm_mlp.2.combined.2.0.weight", "mask_estim.music.norm_mlp.2.combined.2.0.bias", "mask_estim.music.norm_mlp.3.norm.weight", "mask_estim.music.norm_mlp.3.norm.bias", "mask_estim.music.norm_mlp.3.hidden.0.weight", "mask_estim.music.norm_mlp.3.hidden.0.bias", "mask_estim.music.norm_mlp.3.output.0.weight", "mask_estim.music.norm_mlp.3.output.0.bias", "mask_estim.music.norm_mlp.3.combined.0.weight", "mask_estim.music.norm_mlp.3.combined.0.bias", "mask_estim.music.norm_mlp.3.combined.1.0.weight", "mask_estim.music.norm_mlp.3.combined.1.0.bias", "mask_estim.music.norm_mlp.3.combined.2.0.weight", "mask_estim.music.norm_mlp.3.combined.2.0.bias", "mask_estim.music.norm_mlp.4.norm.weight", ...
...
"mask_estim.music.norm_mlp.63.norm.bias", "mask_estim.music.norm_mlp.63.hidden.0.weight", "mask_estim.music.norm_mlp.63.hidden.0.bias", "mask_estim.music.norm_mlp.63.output.0.weight", "mask_estim.music.norm_mlp.63.output.0.bias", "mask_estim.music.norm_mlp.63.combined.0.weight", "mask_estim.music.norm_mlp.63.combined.0.bias", "mask_estim.music.norm_mlp.63.combined.1.0.weight", "mask_estim.music.norm_mlp.63.combined.1.0.bias", "mask_estim.music.norm_mlp.63.combined.2.0.weight", "mask_estim.music.norm_mlp.63.combined.2.0.bias", "mask_estim.sfx.freq_weights/0", "mask_estim.sfx.freq_weights/1", "mask_estim.sfx.freq_weights/2", "mask_estim.sfx.freq_weights/3", "mask_estim.sfx.freq_weights/4", "mask_estim.sfx.freq_weights/5", "mask_estim.sfx.freq_weights/6", "mask_estim.sfx.freq_weights/7", "mask_estim.sfx.freq_weights/8", "mask_estim.sfx.freq_weights/9", "mask_estim.sfx.freq_weights/10", "mask_estim.sfx.freq_weights/11", "mask_estim.sfx.freq_weights/12", "mask_estim.sfx.freq_weights/13", "mask_estim.sfx.freq_weights/14", "mask_estim.sfx.freq_weights/15", "mask_estim.sfx.freq_weights/16", "mask_estim.sfx.freq_weights/17", "mask_estim.sfx.freq_weights/18", "mask_estim.sfx.freq_weights/19", "mask_estim.sfx.freq_weights/20", "mask_estim.sfx.freq_weights/21", "mask_estim.sfx.freq_weights/22", "mask_estim.sfx.freq_weights/23", "mask_estim.sfx.freq_weights/24", "mask_estim.sfx.freq_weights/25", "mask_estim.sfx.freq_weights/26", "mask_estim.sfx.freq_weights/27", "mask_estim.sfx.freq_weights/28", "mask_estim.sfx.freq_weights/29", "mask_estim.sfx.freq_weights/30", "mask_estim.sfx.freq_weights/31", "mask_estim.sfx.freq_weights/32", "mask_estim.sfx.freq_weights/33", "mask_estim.sfx.freq_weights/34", "mask_estim.sfx.freq_weights/35", "mask_estim.sfx.freq_weights/36", "mask_estim.sfx.freq_weights/37", "mask_estim.sfx.freq_weights/38", "mask_estim.sfx.freq_weights/39", "mask_estim.sfx.freq_weights/40", "mask_estim.sfx.freq_weights/41", "mask_estim.sfx.freq_weights/42", "mask_estim.sfx.freq_weights/43", "mask_estim.sfx.freq_weights/44", "mask_estim.sfx.freq_weights/45", "mask_estim.sfx.freq_weights/46", "mask_estim.sfx.freq_weights/47", "mask_estim.sfx.freq_weights/48", "mask_estim.sfx.freq_weights/49", "mask_estim.sfx.freq_weights/50", "mask_estim.sfx.freq_weights/51", "mask_estim.sfx.freq_weights/52", "mask_estim.sfx.freq_weights/53", "mask_estim.sfx.freq_weights/54", "mask_estim.sfx.freq_weights/55", "mask_estim.sfx.freq_weights/56", "mask_estim.sfx.freq_weights/57", "mask_estim.sfx.freq_weights/58", "mask_estim.sfx.freq_weights/59", "mask_estim.sfx.freq_weights/60", "mask_estim.sfx.freq_weights/61", "mask_estim.sfx.freq_weights/62", "mask_estim.sfx.freq_weights/63", "mask_estim.sfx.norm_mlp.0.norm.weight", "mask_estim.sfx.norm_mlp.0.norm.bias", "mask_estim.sfx.norm_mlp.0.hidden.0.weight", "mask_estim.sfx.norm_mlp.0.hidden.0.bias", "mask_estim.sfx.norm_mlp.0.output.0.weight", "mask_estim.sfx.norm_mlp.0.output.0.bias", "mask_estim.sfx.norm_mlp.0.combined.0.weight", "mask_estim.sfx.norm_mlp.0.combined.0.bias", "mask_estim.sfx.norm_mlp.0.combined.1.0.weight", "mask_estim.sfx.norm_mlp.0.combined.1.0.bias", "mask_estim.sfx.norm_mlp.0.combined.2.0.weight", "mask_estim.sfx.norm_mlp.0.combined.2.0.bias", "mask_estim.sfx.norm_mlp.1.norm.weight", "mask_estim.sfx.norm_mlp.1.norm.bias", "mask_estim.sfx.norm_mlp.1.hidden.0.weight", "mask_estim.sfx.norm_mlp.1.hidden.0.bias", "mask_estim.sfx.norm_mlp.1.output.0.weight", "mask_estim.sfx.norm_mlp.1.output.0.bias", "mask_estim.sfx.norm_mlp.1.combined.0.weight", "mask_estim.sfx.norm_mlp.1.combined.0.bias", "mask_estim.sfx.norm_mlp.1.combined.1.0.weight", "mask_estim.sfx.norm_mlp.1.combined.1.0.bias", "mask_estim.sfx.norm_mlp.1.combined.2.0.weight", "mask_estim.sfx.norm_mlp.1.combined.2.0.bias", "mask_estim.sfx.norm_mlp.2.norm.weight", "mask_estim.sfx.norm_mlp.2.norm.bias", "mask_estim.sfx.norm_mlp.2.hidden.0.weight", "mask_estim.sfx.norm_mlp.2.hidden.0.bias", "mask_estim.sfx.norm_mlp.2.output.0.weight", "mask_estim.sfx.norm_mlp.2.output.0.bias", "mask_estim.sfx.norm_mlp.2.combined.0.weight", "mask_estim.sfx.norm_mlp.2.combined.0.bias", "mask_estim.sfx.norm_mlp.2.combined.1.0.weight", "mask_estim.sfx.norm_mlp.2.combined.1.0.bias", "mask_estim.sfx.norm_mlp.2.combined.2.0.weight", "mask_estim.sfx.norm_mlp.2.combined.2.0.bias", "mask_estim.sfx.norm_mlp.3.norm.weight", "mask_estim.sfx.norm_mlp.3.norm.bias", "mask_estim.sfx.norm_mlp.3.hidden.0.weight", "mask_estim.sfx.norm_mlp.3.hidden.0.bias", "mask_estim.sfx.norm_mlp.3.output.0.weight", "mask_estim.sfx.norm_mlp.3.output.0.bias", "mask_estim.sfx.norm_mlp.3.combined.0.weight", "mask_estim.sfx.norm_mlp.3.combined.0.bias", "mask_estim.sfx.norm_mlp.3.combined.1.0.weight", "mask_estim.sfx.norm_mlp.3.combined.1.0.bias", "mask_estim.sfx.norm_mlp.3.combined.2.0.weight", "mask_estim.sfx.norm_mlp.3.combined.2.0.bias", 
...
"mask_estim.sfx.norm_mlp.63.hidden.0.weight", "mask_estim.sfx.norm_mlp.63.hidden.0.bias", "mask_estim.sfx.norm_mlp.63.output.0.weight", "mask_estim.sfx.norm_mlp.63.output.0.bias", "mask_estim.sfx.norm_mlp.63.combined.0.weight", "mask_estim.sfx.norm_mlp.63.combined.0.bias", "mask_estim.sfx.norm_mlp.63.combined.1.0.weight", "mask_estim.sfx.norm_mlp.63.combined.1.0.bias", "mask_estim.sfx.norm_mlp.63.combined.2.0.weight", "mask_estim.sfx.norm_mlp.63.combined.2.0.bias".
        Unexpected key(s) in state_dict: "epoch", "global_step", "pytorch-lightning_version", "state_dict", "loops", "callbacks", "optimizer_states", "lr_schedulers".

        
I've tried setting up a new conda env and re downloaded the repository but I'm getting the same error.
Other models like the bandit plus model did work.

**Comment by ZFTurbo** [comment]
These weights must be fixed before using. Try this script:

```python
    in_path = 'checkpoint-eng.ckpt'
    res = torch.load(in_path)
    res = res['state_dict']
    for el in list(res.keys()):
        print(el)
        if el[:6] == 'model.':
            el_new = el[6:]
            print(el_new)
            res[el_new] = res.pop(el, None)
        if el[:12] == 'loss_handler':
            res.pop(el, None)

    print(list(res.keys()))
    torch.save(res, in_path[:-5] + '_fixed.ckpt')
```

**Comment by Cornox** [comment]
Thank you :) It works now.
