### ISSUE TITLE
Roformer for more than two stems?

### ISSUE THREAD

**Issue by rimb05** [ZFTurbo/Music-Source-Separation-Training#56]
Is roformer only configured for two stems (for example vocal and other)?  I tried to run it with 4 stems (vocal / bass / guitar / drums) but it failed with a tensor size mismatch.  Is there a config setting I'm missing?  Thanks

**Comment by ZFTurbo** [comment]
Sorry for long reply. I added example here:
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/configs/config_musdb18_mel_band_roformer_all_stems.yaml

In short to train for all stems you need to set `num_stems: 4`. Set `instruments:    - drums    - bass    - other    - vocals` and set `target_instrument: null`.

I didn't check it yet myself for correctness. But training process started normally.
