### ISSUE TITLE
MelBand RoFormer Vocal pre-trained model: Missing key(s) in state_dict and size mismatch for mask_estimators

### ISSUE THREAD

**Issue by hunterhogan** [ZFTurbo/Music-Source-Separation-Training#59]
Errors when running inference using the [pre-trained MelBand RoFormer Vocal model](https://github.com/ZFTurbo/Music-Source-Separation-Training?tab=readme-ov-file#pre-trained-models) and the associated Config file.

```python
RuntimeError: Error(s) in loading state_dict for MelBandRoformer:
	Missing key(s) in state_dict: "mask_estimators.0.to_freqs.0.0.4.weight", "mask_estimators.0.to_freqs.0.0.4.bias", ... 
	size mismatch for mask_estimators.0.to_freqs.0.0.2.weight: copying a param with shape torch.Size([56, 768]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for mask_estimators.0.to_freqs.0.0.2.bias: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([768]). ...
```

There are some differences between the file linked in readme and [the file in the main branch](https://github.com/ZFTurbo/Music-Source-Separation-Training/compare/v1.0.0...main#diff-0f7c88b5850180cd7c6e9674f7ac73f98ff3e272bbe9e5228072290acf67093e), but the errors happen with either file.

I don't have much useful information to add, but I did make a Colab notebook to eliminate variables. You can use it, too. It takes about four minutes to install and produce the error. https://colab.research.google.com/drive/1XTTWrs-FJKotFYtH8goTpaT3lIOTKUv1?usp=sharing

**Comment by ZFTurbo** [comment]
I didn't understand which model and whcih config file you mention.

**Comment by hunterhogan** [comment]
Weights
https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.0/model_vocals_mel_band_roformer_sdr_8.42.ckpt

Readme config
https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.0/config_vocals_mel_band_roformer.yaml

And I made cells to try the config files in the main branch:
configs/config_vocals_mel_band_roformer.yaml
configs/config_musdb18_mel_band_roformer.yaml

**Comment by ZFTurbo** [comment]
I think it's better just remove this model from list because it's old and weak.

**Comment by hunterhogan** [comment]
I won't tell your grandparents you said that.

(peace) سلام, 和谐 (group harmony), health, and happiness,

Hunter

Sent from Proton Mail Android

-------- Original Message --------

**Comment by hunterhogan** [comment]
Euthanized.
