### ISSUE TITLE
SCNet-large Frequency Band Configs

### ISSUE THREAD

**Issue by crlandsc** [ZFTurbo/Music-Source-Separation-Training#71]
I was curious how you landed on the following frequency breakdown for the SCNet-large model:
```
  band_SR:
    - 0.225
    - 0.372
    - 0.403
```

The paper mentions the following breakdown as being optimal, which is used in the SCNet model configs in this repo:
```
  band_SR:
    - 0.175
    - 0.392
    - 0.433
```

I was just wondering what the reasoning for the change in the large model was. Thanks!

**Comment by ZFTurbo** [comment]
It was mentioned by author here:
https://github.com/starrytong/SCNet/issues/5

**Comment by crlandsc** [comment]
Ok, thanks so much! Interesting that it wasn't shared in the paper. I was curious if this potentially led to the discrepancy in SDR scores from this repo vs the paper.
