### ISSUE TITLE
Fixed: Demixing full directory slows to a crawl

### ISSUE THREAD

**Issue by Cortexelus** [ZFTurbo/Music-Source-Separation-Training#80]
### Problem
Running on a full directory, with --instrumental flag, will start fast but then slow to a crawl. 

What is happening is the list of instruments to save to WAV files keeps getting an extra "instrumental" appended. So by the 100th track in the directory, `track100_instrumental.wav` is being saved redundantly 100 times

### Solution
The offending line: https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/67af6a467fc9b4c4c35f6a4e9414ec13f61c6b92/inference.py#L97

Should be 
```python
if "instrumental" not in instruments:
   instruments.append('instrumental')
```

**Comment by ZFTurbo** [comment]
I added fix in repo
