### ISSUE TITLE
loss calculation for low_mem roformers

### ISSUE THREAD

**Issue by anvuew** [ZFTurbo/Music-Source-Separation-Training#82]
should low_mem roformers be added here?
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/7e2cc6ecd134f0d108c8c80b0d03ed48f8c549d7/train.py#L274

**Comment by ZFTurbo** [comment]
Yes, but in this case memory requirements grows a lot. I think it must be done as option.

Also for me this code doesn't work correctly - metrics stays relatively at the same place (I did several experiments). I need to understand what is wrong.
