### ISSUE TITLE
RuntimeError: The size of tensor a must match the size of tensor b

### ISSUE THREAD

**Issue by Hwangkop** [ZFTurbo/Music-Source-Separation-Training#83]
Hello, this is my first time trying to use this project for training. I used my own dataset but I got an error during training

Error:
RuntimeError: The size of tensor a (131418) must match the size of tensor b (131584) at non-singleton dimension 1

Config:
audio:
chunk_size: 131584
dim_f: 1024
dim_t: 256
hop_length: 512
n_fft: 2048
num_channels: 1
sample_rate: 44100
min_mean_abs: 0.000

Each song in my training and validation datasets is longer than 1 minute. What is the chunk_size in this configuration used for? Do I need to split my dataset into chunks of chunk_size?

Please help me, thank you!

**Comment by ZFTurbo** [comment]
Hello. What is the model type? Chunk size must be equal to (dim_t - 1) * hop_length

**Comment by Hwangkop** [comment]
> Hello. What is the model type? Chunk size must be equal to (dim_t - 1) * hop_length

Thank you for your reply, it gave me hope.

I am now trying to train with the data transformed by musdb18

My training command parameters:
  model_type = "mel_band_roformer"
  config_path = "configs\config_musdb18_mel_band_roformer.yaml"
  results_path = "results"
  data_path = "musdb18_all5"
  valid_path = "validation"
  num_workers = "4"
  device_ids = "0"

I modified "configs\config_musdb18_mel_band_roformer.yaml"
  training:
    batch_size: 1
    instruments:
    - instrumental
    - vocal
    target_instrument: vocal

Use the default parameters:
  audio:
    chunk_size: 131584
    dim_f: 1024
    dim_t: 256
    hop_length: 512
    n_fft: 2048
    num_channels: 2
    sample_rate: 44100
    min_mean_abs: 0.001

But chunk_size is not equal to (256 - 1) * 512?

I attached my training log, please help me check it, thank you very much!
[train_20241016_145359.log](https://github.com/user-attachments/files/17390782/train_20241016_145359.log)

**Comment by ZFTurbo** [comment]
For MelBand it's different. Parmeters from 'model' part are used. You can make inspiration from Kimberley's roformer config:
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml

**Comment by Hwangkop** [comment]
> For MelBand it's different. Parmeters from 'model' part are used. You can make inspiration from Kimberley's roformer config: https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml

Thanks again for your reply

I tried 
model_type: mel_band_roformer
configs\KimberleyJensen\config_vocals_mel_band_roformer_kj.yaml
Only changed:
batch_size: 1
instruments:
- vocal
- instrumental
target_instrument: vocal

model_type: mdx23c
configs\config_musdb18_mdx23c.yaml
Only changed:
batch_size: 1
instruments:
- vocal
- instrumental

inference:
batch_size: 1
dim_t: 256
num_overlap: 2

But all reported same errors：
ValueError: operands could not be broadcast together with shapes (1,2,12259556) (1,2,12259535)

My training data
song1/ duration：3:56
 - vocal.wav
 - instrumental.wav 

song2/ duration: 3:07 
 - vocal.wav
 - instrumental.wav 

validation data: 
song1/ duration: 3:37 
 - vocal.wav 
 - instrumental.wav
 - mixture.wav
 
I am really confused

**Comment by ZFTurbo** [comment]
Did you have the same error for 2 models? Can you print full error message (with line numbers etc)?

**Comment by Hwangkop** [comment]
> Did you have the same error for 2 models? Can you print full error message (with line numbers etc)?

When the first epoch ends, then  valid and then an same error is reported

100%|��������������������| 8/8 [00:14<00:00,  1.82s/it, loss=0, avg_loss=0]

  0%|          | 0/1 [00:00<?, ?it/s]Process Process-22:
Traceback (most recent call last):
  File "E:\ProgramData\miniconda3\envs\gptvit\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "E:\ProgramData\miniconda3\envs\gptvit\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\app\Music-Source-Separation-Training\valid.py", line 238, in valid_mp
    single_metrics = proc_list_of_files([path], m1, args, config, device, False, False)
  File "D:\app\Music-Source-Separation-Training\valid.py", line 135, in proc_list_of_files
    track_metrics = get_metrics(
  File "D:\app\Music-Source-Separation-Training\utils.py", line 347, in get_metrics
    result['sdr'] = sdr(references, estimates)[0]
  File "D:\app\Music-Source-Separation-Training\utils.py", line 241, in sdr
    den = np.sum(np.square(references - estimates), axis=(1, 2))
ValueError: operands could not be broadcast together with shapes (1,2,12259556) (1,2,12259535)

**Comment by ZFTurbo** [comment]
Very strange. Can you run `inference.py` on any track?
Using this config:
https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml
And this weights:
https://huggingface.co/KimberleyJSN/melbandroformer/resolve/main/MelBandRoformer.ckpt

**Comment by Hwangkop** [comment]
> Very strange. Can you run `inference.py` on any track? Using this config: https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml And this weights: https://huggingface.co/KimberleyJSN/melbandroformer/resolve/main/MelBandRoformer.ckpt

I use these models regularly and there are no problems.
I have found the problem now, it is because the lengths of stems are little different.
Thank you very much for your support again!
