### ISSUE TITLE
GPU for inference

### ISSUE THREAD

**Issue by Recalf** [ZFTurbo/Music-Source-Separation-Training#86]
Hi,
I want to use bandit plus, but when i use Music source seperation inference.py , its very slow, it shows 0% gpu utilization (but its using all of my gpu vrams). does the inference mode uses "only CPU" ? or the bandit plus model doesnt support gpu utilization ? or its another problem i should look into? 
thx

**Comment by ZFTurbo** [comment]
Hello. Try to reduce inference/batch_size in config.

**Comment by Recalf** [comment]
nope didnt work, its not using the gpu (except its vram), is this normal ? because other ai stuff used it fully

**Comment by ZFTurbo** [comment]
No it's not normal it should use GPU. If VRAM is used it means GPU is used. Which batch size do you use? How many GPU memory do you have?

**Comment by Recalf** [comment]
I use right now this config  (i used at first when i messaged you the default, which was batch size 1 and num overlap 4, it takes maybe 1:30h for every 20min audio)  :
inference:
  batch_size: 3
  dim_t: 256
  num_overlap: 2
 and i have a gtx 1650 4gb vram
 
 this happens
![image](https://github.com/user-attachments/assets/7a402238-5127-4b19-b9db-1362d61f31d2)
![image](https://github.com/user-attachments/assets/a3403a64-46c3-4a41-9321-9d496c46e1d3)

**Comment by Recalf** [comment]
yeah i checked batch size 1 it gave me the same issue, i tried other models, also the same.

**Comment by Recalf** [comment]
Im baffled right now, i tried demucs gui right now and its has the same issue (but still has the same speed i talked about), i dont remember where i saw a local ai using 100% in processes tab, i dont know if its related to audio seperation.
idk if the speed of demucs gui is just because it uses maybe lower settings in the models config (but just with different names), i dont know what this translates to in yaml config files.
![image](https://github.com/user-attachments/assets/75e16fb7-65cc-4aa6-bd9a-f55a087d3378)

**Comment by ZFTurbo** [comment]
To see real load of your GPU you need to switch from Copy to Cuda in your task manager

![изображение](https://github.com/user-attachments/assets/50b3b046-dbc8-42b1-ac71-711c5700fce2)

**Comment by Recalf** [comment]
oh you're right, okay then that means i should just lower the dim_t or/and num_overlap if i want it to be faster, thanks for your responses.
![image](https://github.com/user-attachments/assets/8f51a159-9aca-4fa1-be84-4280cd3132df)

**Comment by Recalf** [comment]
oh you're right, okay then that means i should just lower the dim_t or/and num_overlap if i want it to be faster, thanks for your responses.
![image](https://github.com/user-attachments/assets/2f4eb0e8-c5d9-4e5d-b77e-8fb3e62f1d33)
