### ISSUE TITLE
Inference killed by OOM reaper when using checkpoints

### ISSUE THREAD

**Issue by aguadoenzo** [ZFTurbo/Music-Source-Separation-Training#9]
I'm running the following command on a server with 32GB of RAM, 8GB of swap, **without** a GPU and it's getting killed after a few seconds. It will fill both memory and swap completely before getting killed.

`python3 inference.py --model_type htdemucs --config_path configs/config_musdb18_htdemucs.yaml --start_check_point checkpoints/htdemucs_ft_bass.th --input_folder /input --store_dir /output/`

Is there a way to limit the amount of RAM being used ?

**Comment by ZFTurbo** [comment]
For demucs model I didn't implement batching, so in current codebase there are 2 ways: 
1) you can give smaller song on input. For example split it on smaller parts yourself
2) lower setting from 4 to 1:
```
inference:
  num_overlap: 4
```

Probably I will add batching to control memory for htdemucs later.
