### ISSUE TITLE
Redistribution of pre-trained models in open source project?

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [ZFTurbo/Music-Source-Separation-Training#90]
Hello! Awesome project -- I would love to add some of the pre-trained models that you give links to in top-level README as selectable models / features in our AI plugins for Audacity project ( https://github.com/intel/openvino-plugins-ai-audacity ). 

Is this okay? I didn't see any license information posted for the linked models. Would it be possible to add an open source license to your project (like MIT, etc.)? 

Thanks!
Ryan

**Comment by ZFTurbo** [comment]
Hello, not all models were posted by me. While I can add some open license on repo I think I can't really decide on each model. Are you interested in some particular models to add?

**Comment by RyanMetcalfeInt8** [comment]
Thanks!

> Are you interested in some particular models to add?

Yes, at least initially I am interested in these ones:
* MelBand Roformer ([KimberleyJensen](https://github.com/KimberleyJensen/) edition) for Vocal Extraction
* MelBand Roformer ([anvuew](https://github.com/anvuew) edition) for Reverb Removal

And also potentially these ones.. still evaluating them:
* MelBand Roformer Denoise (by [aufr33](https://github.com/aufr33)) 
* MelBand Roformer Denoise Aggressive (by [aufr33](https://github.com/aufr33))

And outside of the model weights themselves, I'll need to port some of the python bits to C++ (various pieces from https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/utils.py, https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/models/bs_roformer/mel_band_roformer.py, etc). And this is because I distribute Audacity plugins as pure-C++ compiled DLLs, which makes distribution a bit easier than python (IMO). 

Thanks!
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Just to follow up here -- as for the py code in this repo, could you at least add open source license that pertains to that? For example, It seems https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/models/bs_roformer/mel_band_roformer.py is derived from https://github.com/lucidrains/BS-RoFormer/blob/main/bs_roformer/mel_band_roformer.py (which is MIT), so wis your derivation of it also MIT?

**Comment by ZFTurbo** [comment]
I added licence 2 days ago:
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/LICENSE

**Comment by RyanMetcalfeInt8** [comment]
Oh my bad, I missed that! Thank you!
