### ISSUE TITLE
CPU vs GPU

### ISSUE THREAD

**Issue by AirJCovers34** [ZFTurbo/Music-Source-Separation-Training#93]
How can I specify for the program to use the GPU instead of the CPU?

![image](https://github.com/user-attachments/assets/f17bcf5d-5691-418e-91cd-0fe55fd6a207)

**Comment by ZFTurbo** [comment]
Code automatically uses CUDA if it's avialable.

**Comment by AirJCovers34** [comment]
Ok. That was my mistake: My Cuda wasn’t installed in the venv I’m using to run the script.
Thank you.
