### ISSUE TITLE
What is the best model for OpenWhisper?

### ISSUE THREAD

**Issue by montvid** [ZFTurbo/Music-Source-Separation-Training#95]
I came to know that in order to use OpenWhisper to transcribe accurately one needs to seperate the voice from other parts of the audio and to remove silence with a pre-trained enterprise-grade Voice Activity Detector.

Now what model does voice seperation the best for OpenWhisper to understand could be a nice test case in the main table. Maybe someone could share their favorite?

I see https://mvsep.com uses OpenWhisper - What models does the site use to clean the audio as without cleaning Whisper spits out mostly garbage.
Edit: https://mvsep.com uses MDX23C - but how does one clean enough the audio without a VAD for Whisper not to hallucinate?

**Comment by ZFTurbo** [comment]
We use our own BS Roformer model similar to BS Roformer (viperx) vocal model in this list:
https://github.com/ZFTurbo/Music-Source-Separation-Training?tab=readme-ov-file#vocal-models

**Comment by montvid** [comment]
> We use our own BS Roformer model similar to BS Roformer (viperx) vocal model in this list: https://github.com/ZFTurbo/Music-Source-Separation-Training?tab=readme-ov-file#vocal-models

Thanks for your reply. BS Roformer model seems to be the best for my audio files as MDX23C, MelBand Roformer ([KimberleyJensen](https://github.com/KimberleyJensen/) edition) is not as precise for OpenWhisper/FasterWhisper to understand. Tried all of them on https://mvsep.com/ nice - just got some hallucinations during silence in audio - trying to fix those with https://github.com/snakers4/silero-vad. Experimenting with whisper.cpp seems to give different results than fasterwhisper. Still no perfect solution with zero hallucinations. Thanks for your work!
